apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: avengers-backend
  namespace: avengers
spec:
  project: default
  source:
    repoURL: https://github.com/sourav977/avengers-backend-k8s-manifest.git
    targetRevision: HEAD
    path: dev/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: avengers

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
